#!/usr/bin/env python3
"""Mine Reddit for story-candidate posts across 3 sub-genre clusters.

Pulls top/hot posts from 6 subreddits across multiple time windows, applies
hard filters, scores each candidate by 9 measurable signals (every component
broken out in the report), proposes hook + setting variants, and writes a
ranked markdown + JSON report to output/research/.

Supports --stub <id> to materialize ONE pre-filled queue stub from a candidate,
and --stub-top N to batch-stub the top N per cluster (round-robin S/R/H so the
existing orchestrator's sub-genre balancer feeds cleanly).

NEVER copies selftext verbatim into queue files — Premise is always a
structural paraphrase ("Narrator [verb]. [Inciting noun]. [Escalation verb].")
generated by deterministic templates. Source URL goes into Notes for the
writer to re-read at production time and apply the playbook's rewrite rule.

Usage:
    /research-stories                              # bulk mode (default)
    python scripts/research_reddit_stories.py --cluster horror --limit 5
    python scripts/research_reddit_stories.py --stub-top 5             # 15 new stubs
    python scripts/research_reddit_stories.py --stub-top 5 --dry-run
    python scripts/research_reddit_stories.py --stub <candidate_id>
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from collections import Counter, defaultdict
from datetime import date, datetime, timezone
from pathlib import Path

import requests

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _env import load_dotenv  # noqa: E402
from _atomic import atomic_write_json, atomic_write_text  # noqa: E402

load_dotenv(PROJECT_ROOT / ".env")

QUEUE_DIR = PROJECT_ROOT / "story_queue"
RESEARCH_DIR = PROJECT_ROOT / "output" / "research"
REJECTED_PATH = RESEARCH_DIR / "_rejected.json"

# Polite UA — Reddit blocks generic Python-urllib UAs. Identifies the bot
# clearly so they can throttle/block surgically rather than the whole IP.
USER_AGENT = "drop-channel-research/0.1 (ShortBaldFatNoCareer YouTube Shorts pipeline)"

# Subreddit → sub-genre cluster mapping. Edit at top-of-file for easy tuning.
SUB_CLUSTERS = {
    "horror":   {"letter": "H", "subreddits": ["nosleep", "shortscarystories"]},
    "reddit":   {"letter": "R", "subreddits": ["AmItheAsshole", "relationships"]},
    "survival": {"letter": "S", "subreddits": ["LetsNotMeet", "creepyencounters"]},
}

# Rankings × time windows to mine per subreddit. Default = bulk.
DEFAULT_WINDOWS = [
    ("top", "week"),
    ("top", "month"),
    ("top", "year"),
    ("hot", None),  # no t param for hot
]

POSTS_PER_REQUEST = 100  # Reddit max
REQUEST_SPACING_SEC = 1.5  # stays well under unauth limit of ~60/min

# Hard filters
MIN_SELFTEXT_CHARS = 200
MAX_SELFTEXT_CHARS = 8000
FLAIR_DROPLIST = {"Series", "Meta", "Mod Post", "Update", "Mod Announcement"}
DELETED_MARKERS = ("[removed]", "[deleted]", "tl;dr only")

# Hook-extraction patterns per cluster
HORROR_WRONG_DETAIL = re.compile(
    r"\b(but|except|however|wait|then|actually|until)\b[^.!?\n]{0,80}?"
    r"(footprints|figure|shadow|sound|sounds|whisper|smile|reflection|hand|hands|eyes|"
    r"door|window|mirror|floor|ceiling|wall|stairs|key|lock|noise|breathing|movement)",
    re.IGNORECASE,
)
REDDIT_VIOLATION = re.compile(
    r"\bmy\s+(husband|wife|boyfriend|girlfriend|partner|mom|mother|dad|father|sister|brother|"
    r"son|daughter|friend|neighbor|coworker|boss|landlord|roommate|sister-in-law|brother-in-law|"
    r"mother-in-law|father-in-law)\s+"
    r"(did|said|told|wanted|brought|invited|kicked|threw|destroyed|broke|stole|hit|threatened|"
    r"banned|fired|dumped|cheated|left|forced|made me|asked me|told me|started)\b[^.!?\n]{0,80}",
    re.IGNORECASE,
)
SURVIVAL_THREAT = re.compile(
    r"\b(saw|heard|noticed|spotted|found|discovered|smelled|felt|woke up to|realized)\b\s+"
    r"[^.!?\n]{0,60}?"
    r"(footprints|figure|shadow|smoke|light|lights|movement|sound|sounds|knock|knocking|"
    r"breathing|whisper|whispers|tracks|blood|noise|noises|outline|silhouette|eyes|glow)",
    re.IGNORECASE,
)

# Per-cluster setting swap tables for alternative-framing proposals
SETTING_SWAPS = {
    "H": {
        "basement":  ["crawlspace", "attic", "root cellar"],
        "attic":     ["basement", "crawlspace", "hayloft"],
        "house":     ["cottage", "trailer", "rented airbnb"],
        "bedroom":   ["guest room", "childhood bedroom", "dorm room"],
        "mirror":    ["window reflection", "phone screen", "darkened TV"],
        "forest":    ["national park trail", "logging road", "marsh"],
        "hospital":  ["urgent care clinic", "abandoned asylum", "dental office"],
    },
    "R": {
        "wedding":   ["bridal shower", "engagement party", "rehearsal dinner"],
        "birthday":  ["graduation", "promotion party", "baby shower"],
        "fence":     ["security camera", "no-trespass sign", "shared driveway"],
        "money":     ["inheritance", "rent share", "vacation cost"],
        "house":     ["condo", "duplex", "rental"],
        "child":     ["stepchild", "niece", "godchild"],
    },
    "S": {
        "cabin":     ["cliffside trailer", "fire lookout tower", "ice-fishing shack"],
        "tent":      ["truck bed", "lean-to", "snow cave"],
        "trail":     ["fire road", "service road", "river bottom"],
        "boat":      ["kayak", "canoe", "raft"],
        "campsite":  ["pull-off", "trailhead parking", "primitive camp"],
        "mountain":  ["foothill", "ridge", "ravine"],
    },
}

# Voice + model assignments per sub-genre letter (mirrors story_script_writer.py)
VOICE_ASSIGNMENTS = {
    "S": {"voice": "Charlie", "model": "eleven_turbo_v2"},
    "R": {"voice": "Brian",   "model": "eleven_multilingual_v2"},
    "H": {"voice": "Daniel",  "model": "eleven_multilingual_v2"},
}


# ---------------------------------------------------------------------------
# HTTP fetcher (raw, polite)
# ---------------------------------------------------------------------------

def fetch_json(url: str, retries: int = 3) -> dict | None:
    """GET with polite UA + exponential backoff on 429/5xx. Returns parsed JSON or None."""
    backoff = 2.0
    for attempt in range(retries):
        try:
            resp = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=20)
        except (requests.RequestException, OSError) as e:
            print(f"    [warn] network error: {e} (attempt {attempt+1}/{retries})", file=sys.stderr)
            time.sleep(backoff)
            backoff *= 2
            continue

        if resp.status_code == 429:
            retry_after = float(resp.headers.get("Retry-After", backoff))
            print(f"    [warn] 429 rate-limit, sleeping {retry_after:.0f}s", file=sys.stderr)
            time.sleep(retry_after)
            backoff *= 2
            continue
        if resp.status_code >= 500:
            print(f"    [warn] {resp.status_code} server error, retry in {backoff:.0f}s", file=sys.stderr)
            time.sleep(backoff)
            backoff *= 2
            continue
        if resp.status_code != 200:
            print(f"    [warn] HTTP {resp.status_code} for {url}", file=sys.stderr)
            return None

        try:
            return resp.json()
        except ValueError:
            return None
    return None


def mine_subreddit(sub: str, ranking: str, window: str | None) -> list[dict]:
    """Return raw post dicts from a /r/<sub>/<ranking>.json fetch."""
    if window:
        url = f"https://www.reddit.com/r/{sub}/{ranking}.json?t={window}&limit={POSTS_PER_REQUEST}"
    else:
        url = f"https://www.reddit.com/r/{sub}/{ranking}.json?limit={POSTS_PER_REQUEST}"

    payload = fetch_json(url)
    if not payload:
        return []
    children = payload.get("data", {}).get("children", [])
    return [c.get("data", {}) for c in children if isinstance(c, dict)]


# ---------------------------------------------------------------------------
# Filtering + scoring
# ---------------------------------------------------------------------------

def passes_hard_filters(post: dict) -> tuple[bool, str]:
    """Return (pass, reason). Reason is empty on pass."""
    if post.get("stickied"):
        return False, "stickied"
    if post.get("over_18"):
        return False, "over_18"
    if post.get("removed_by_category"):
        return False, f"removed:{post['removed_by_category']}"
    if not post.get("is_self"):
        return False, "link_post"
    selftext = post.get("selftext", "") or ""
    if not selftext.strip():
        return False, "empty_selftext"
    lower = selftext.lower()
    for marker in DELETED_MARKERS:
        if marker in lower[:200]:  # only check head, real posts can mention these words later
            return False, f"marker:{marker}"
    if len(selftext) < MIN_SELFTEXT_CHARS:
        return False, f"too_short:{len(selftext)}c"
    if len(selftext) > MAX_SELFTEXT_CHARS:
        return False, f"too_long:{len(selftext)}c"
    flair = post.get("link_flair_text") or ""
    if flair in FLAIR_DROPLIST:
        return False, f"flair:{flair}"
    return True, ""


def compute_score(post: dict, cluster: str) -> dict:
    """Return {component_name: value, ..., total: float}. Every component is broken out."""
    ups = post.get("ups", 0) or 0
    num_comments = post.get("num_comments", 0) or 0
    awards = post.get("total_awards_received", 0) or 0
    gilded = post.get("gilded", 0) or 0
    crossposts = post.get("num_crossposts", 0) or 0
    created_utc = float(post.get("created_utc", 0))
    selftext = post.get("selftext", "") or ""
    flair = post.get("link_flair_text") or ""

    now = datetime.now(timezone.utc).timestamp()
    age_seconds = max(now - created_utc, 1.0)
    age_hours = age_seconds / 3600
    age_days = age_seconds / 86400

    ups_score = min(1.0, ups / 5000) * 25
    engagement_score = min(1.0, num_comments / max(ups, 1) * 5) * 15
    velocity_score = min(1.0, ups / age_hours / 50) * 15
    awards_score = min(1.0, awards / 5) * 10
    freshness_score = max(0.0, (30 - age_days) / 30) * 5
    sl = len(selftext)
    if 500 <= sl <= 3000:
        length_score = 15.0
    elif 200 <= sl < 500 or 3000 < sl <= 6000:
        length_score = 8.0
    else:
        length_score = 0.0
    crosspost_score = min(1.0, crossposts / 10) * 5
    gilded_score = min(1.0, gilded / 3) * 5

    verdict_score = 0.0
    if cluster == "reddit" and flair in {"Asshole", "Not the A-hole", "Everyone Sucks", "No A-holes here"}:
        verdict_score = 10.0

    total = (ups_score + engagement_score + velocity_score + awards_score +
             freshness_score + length_score + crosspost_score + gilded_score + verdict_score)

    return {
        "ups_score": round(ups_score, 2),
        "engagement_score": round(engagement_score, 2),
        "velocity_score": round(velocity_score, 2),
        "awards_score": round(awards_score, 2),
        "freshness_score": round(freshness_score, 2),
        "length_score": round(length_score, 2),
        "crosspost_score": round(crosspost_score, 2),
        "gilded_score": round(gilded_score, 2),
        "verdict_score": round(verdict_score, 2),
        "total": round(total, 2),
        "_meta": {
            "ups": ups, "num_comments": num_comments, "awards": awards,
            "gilded": gilded, "crossposts": crossposts, "age_hours": round(age_hours, 1),
            "age_days": round(age_days, 1), "selftext_chars": sl, "flair": flair,
        },
    }


# ---------------------------------------------------------------------------
# Hook + setting extraction
# ---------------------------------------------------------------------------

def _truncate_words(s: str, max_words: int = 12) -> str:
    words = s.split()
    if len(words) <= max_words:
        return s.strip(" ,.")
    return " ".join(words[:max_words]).strip(" ,.")


def extract_hook_variants(post: dict, cluster: str) -> list[str]:
    """Return up to 3 proposed hook lines following the cluster's TikTok-first formula."""
    title = (post.get("title") or "").strip()
    selftext = (post.get("selftext") or "")
    body = selftext[:1500]  # only scan head; hooks live near the top
    variants: list[str] = []

    if cluster == "horror":
        # "Wrong detail" — scan for clauses with contrast marker + concrete noun
        for m in HORROR_WRONG_DETAIL.finditer(body):
            clause = m.group(0)
            short = _truncate_words(clause, 10)
            if short and short not in variants:
                variants.append(short.capitalize() + ".")
            if len(variants) >= 3:
                break
        # Fallback: derive from title
        if len(variants) < 3 and title:
            t = _truncate_words(title.lstrip(":-—– "), 10)
            if t and t not in variants:
                variants.append(t.rstrip(" .?!") + ".")

    elif cluster == "reddit":
        # "[Violation in 5 words]. AITA?"
        for m in REDDIT_VIOLATION.finditer(body):
            clause = m.group(0)
            short = _truncate_words(clause, 9)
            if short:
                hook = short.capitalize().rstrip(" .?!") + ". AITA?"
                if hook not in variants:
                    variants.append(hook)
            if len(variants) >= 3:
                break
        # Fallback: derive a violation from the title
        if len(variants) < 3:
            t = title.replace("AITA for", "").replace("AITAH for", "").replace("WIBTA for", "").strip(" -:?,. ")
            if t:
                short = _truncate_words(t, 9)
                hook = short.capitalize().rstrip(" .?!") + ". AITA?"
                if hook not in variants:
                    variants.append(hook)

    elif cluster == "survival":
        # "[Threat verb-of-perception] [concrete noun]"
        for m in SURVIVAL_THREAT.finditer(body):
            clause = m.group(0)
            short = _truncate_words(clause, 10)
            if short and short not in variants:
                variants.append(short.capitalize().rstrip(" .?!") + ".")
            if len(variants) >= 3:
                break
        # Fallback: title-based
        if len(variants) < 3 and title:
            t = _truncate_words(title.lstrip(":-—– "), 10)
            if t and t not in variants:
                variants.append(t.rstrip(" .?!") + ".")

    # Always provide at least one option — empty hook list is unhelpful in the report
    if not variants and title:
        variants.append(_truncate_words(title, 12).rstrip(" .?!") + ".")
    return variants[:3]


def extract_setting_variants(post: dict, cluster: str) -> list[str]:
    """Return up to 3 alternative-framing settings by swapping nouns from the swap table."""
    letter = SUB_CLUSTERS[cluster]["letter"]
    swaps = SETTING_SWAPS.get(letter, {})
    blob = ((post.get("title") or "") + " " + (post.get("selftext") or "")[:800]).lower()
    suggestions: list[str] = []
    for base_noun, alternatives in swaps.items():
        if base_noun in blob:
            suggestions.append(f"swap '{base_noun}' → {', '.join(alternatives)}")
            if len(suggestions) >= 3:
                break
    if not suggestions:
        # Even when no noun matches, give the writer a baseline
        suggestions.append("(no canonical noun matched — pick a less-clichéd setting at writing time)")
    return suggestions


# ---------------------------------------------------------------------------
# Structural-paraphrase Premise generator (NEVER copies selftext verbatim)
# ---------------------------------------------------------------------------

def structural_paraphrase(post: dict, cluster: str) -> str:
    """Generate a 1-2 sentence structural summary — uses only deterministic templates.

    The phrasing is intentionally generic so it can't accidentally repeat the
    Reddit author's prose. The writer paraphrases for real at production time
    using the source URL in Notes.
    """
    title = (post.get("title") or "").strip()
    letter = SUB_CLUSTERS[cluster]["letter"]

    if letter == "H":
        return (
            f"Original horror micro-fiction inspired by the structural shape of "
            f"this post (NOT the prose). The writer must invent the entity, "
            f"setting details, and dialogue at production time. Source provided "
            f"in Notes for tone reference only."
        )
    if letter == "R":
        return (
            f"AITA-style dramatization. Narrator describes a violation involving a "
            f"close-relation (paraphrase the source — do NOT quote). Hook leads with "
            f"the violation; the AITA question lands last. Anonymize all names + "
            f"locations. Title pattern: \"{_truncate_words(title, 8)}…\""
        )
    if letter == "S":
        return (
            f"First-person survival/creepy-encounter retelling. Narrator describes a "
            f"threat-perception moment (footprints, sounds, figure, etc) in a remote "
            f"or isolated setting. Original prose only — use source URL for tone, "
            f"never for phrasing."
        )
    return f"Story inspired by Reddit post titled \"{_truncate_words(title, 10)}…\". Writer must paraphrase."


# ---------------------------------------------------------------------------
# Queue de-dup + rejection memory
# ---------------------------------------------------------------------------

def load_existing_queue_urls() -> set[str]:
    """Scan story_queue/*.md for any reddit.com URLs in Notes — used to dedupe."""
    urls = set()
    if not QUEUE_DIR.exists():
        return urls
    pattern = re.compile(r"https?://(?:www\.)?reddit\.com/r/\w+/comments/(\w+)", re.IGNORECASE)
    for p in QUEUE_DIR.glob("SY_*.md"):
        if p.name.startswith("SY_TEMPLATE"):
            continue
        for m in pattern.finditer(p.read_text()):
            urls.add(m.group(1))  # the post id
    return urls


def load_rejected() -> set[str]:
    if not REJECTED_PATH.exists():
        return set()
    try:
        data = json.loads(REJECTED_PATH.read_text())
        return {entry["id"] for entry in data if "id" in entry}
    except (json.JSONDecodeError, OSError, KeyError):
        return set()


def append_rejected(post_id: str, reason: str) -> None:
    RESEARCH_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    if REJECTED_PATH.exists():
        try:
            entries = json.loads(REJECTED_PATH.read_text())
        except (json.JSONDecodeError, OSError):
            entries = []
    entries.append({"id": post_id, "reason": reason, "date": date.today().isoformat()})
    atomic_write_json(REJECTED_PATH, entries, indent=2)


def next_sy_number() -> int:
    """Scan story_queue/ for max SY_NN_ and return max+1."""
    if not QUEUE_DIR.exists():
        return 1
    nums = []
    pat = re.compile(r"^SY_(\d{2,3})_")
    for p in QUEUE_DIR.glob("SY_*.md"):
        m = pat.match(p.name)
        if m:
            nums.append(int(m.group(1)))
    return (max(nums) + 1) if nums else 1


def slugify(s: str, max_len: int = 24) -> str:
    """Lowercase, alphanumeric+underscore only, capped."""
    s = re.sub(r"[^a-z0-9]+", "_", s.lower())
    s = re.sub(r"_+", "_", s).strip("_")
    return s[:max_len] or "untitled"


# ---------------------------------------------------------------------------
# Bulk mining → ranked candidate list
# ---------------------------------------------------------------------------

def mine_all(cluster_filter: str | None, windows: list[tuple[str, str | None]]) -> dict[str, list[dict]]:
    """Return {cluster_name: [candidate_dict, ...]} sorted desc by total score."""
    candidates_by_cluster: dict[str, list[dict]] = defaultdict(list)
    seen_ids: set[str] = set()
    existing_urls = load_existing_queue_urls()
    rejected = load_rejected()

    n_requests = 0
    total_raw = 0
    filtered_counter: Counter[str] = Counter()

    for cluster_name, info in SUB_CLUSTERS.items():
        if cluster_filter and cluster_name != cluster_filter:
            continue
        for sub in info["subreddits"]:
            for ranking, window in windows:
                if n_requests > 0:
                    time.sleep(REQUEST_SPACING_SEC)
                print(f"  [mine] r/{sub} {ranking}{f'?t={window}' if window else ''}", file=sys.stderr)
                raw_posts = mine_subreddit(sub, ranking, window)
                n_requests += 1
                total_raw += len(raw_posts)

                for post in raw_posts:
                    pid = post.get("id")
                    if not pid or pid in seen_ids:
                        continue
                    seen_ids.add(pid)
                    if pid in existing_urls:
                        filtered_counter["already_queued"] += 1
                        continue
                    if pid in rejected:
                        filtered_counter["previously_rejected"] += 1
                        continue
                    ok, reason = passes_hard_filters(post)
                    if not ok:
                        filtered_counter[reason] += 1
                        continue

                    score = compute_score(post, cluster_name)
                    candidate = {
                        "id": pid,
                        "cluster": cluster_name,
                        "cluster_letter": info["letter"],
                        "subreddit": sub,
                        "title": post.get("title", "").strip(),
                        "selftext": post.get("selftext", ""),
                        "url": f"https://www.reddit.com{post.get('permalink', '')}",
                        "score": score,
                        "hook_variants": extract_hook_variants(post, cluster_name),
                        "setting_variants": extract_setting_variants(post, cluster_name),
                        "premise_paraphrase": structural_paraphrase(post, cluster_name),
                    }
                    candidates_by_cluster[cluster_name].append(candidate)

    print(f"\n  [mine] {n_requests} requests, {total_raw} raw posts, "
          f"{sum(len(v) for v in candidates_by_cluster.values())} candidates after filters", file=sys.stderr)
    if filtered_counter:
        top_reasons = ", ".join(f"{r}={n}" for r, n in filtered_counter.most_common(5))
        print(f"  [mine] filter breakdown (top 5): {top_reasons}", file=sys.stderr)

    # Sort each cluster's candidates descending by total score
    for cluster_name in candidates_by_cluster:
        candidates_by_cluster[cluster_name].sort(key=lambda c: c["score"]["total"], reverse=True)
    return dict(candidates_by_cluster)


# ---------------------------------------------------------------------------
# Report writers
# ---------------------------------------------------------------------------

def write_markdown_report(candidates_by_cluster: dict[str, list[dict]], limit: int) -> Path:
    RESEARCH_DIR.mkdir(parents=True, exist_ok=True)
    out_path = RESEARCH_DIR / f"candidates_{date.today().isoformat()}.md"

    lines: list[str] = []
    lines.append(f"# Reddit Story Candidates — {date.today().isoformat()}")
    lines.append("")
    lines.append(
        f"Generated by `scripts/research_reddit_stories.py`. Top **{limit}** per cluster "
        f"({len(candidates_by_cluster) * limit} total target)."
    )
    lines.append("")
    lines.append("> ⚠️ **Anti-plagiarism reminder:** every `selftext` block below is COPYRIGHTED by the Reddit author. "
                 "It's collapsed in `<details>` specifically to deter copy-paste. The stub Premise is a "
                 "structural paraphrase — at production time the writer re-reads the source URL and applies "
                 "the playbook's rewrite rule. NEVER ship verbatim Reddit prose.")
    lines.append("")

    for cluster_name in ("horror", "reddit", "survival"):
        items = candidates_by_cluster.get(cluster_name, [])
        if not items:
            continue
        letter = SUB_CLUSTERS[cluster_name]["letter"]
        lines.append(f"## {cluster_name.title()} cluster ({letter}) — {len(items)} candidates ranked")
        lines.append("")

        for rank, c in enumerate(items[:limit], 1):
            s = c["score"]
            meta = s["_meta"]
            lines.append(f"### #{rank} — {c['title']}")
            lines.append("")
            lines.append(f"- **Score**: **{s['total']}** / 100")
            lines.append(f"- **Source**: [{c['url']}]({c['url']}) — r/{c['subreddit']}")
            lines.append(f"- **Post id**: `{c['id']}`")
            lines.append("")
            lines.append("| Signal | Score | Raw |")
            lines.append("|---|---|---|")
            lines.append(f"| ups            | {s['ups_score']}        | {meta['ups']} ups |")
            lines.append(f"| engagement     | {s['engagement_score']} | {meta['num_comments']} comments ({meta['num_comments']/max(meta['ups'],1):.2f}/up) |")
            lines.append(f"| velocity       | {s['velocity_score']}   | {meta['ups']/max(meta['age_hours'],1):.1f} ups/hr ({meta['age_hours']:.0f}h old) |")
            lines.append(f"| awards         | {s['awards_score']}     | {meta['awards']} awards |")
            lines.append(f"| freshness      | {s['freshness_score']}  | {meta['age_days']:.0f} days old |")
            lines.append(f"| length         | {s['length_score']}     | {meta['selftext_chars']} chars |")
            lines.append(f"| crossposts     | {s['crosspost_score']}  | {meta['crossposts']} crossposts |")
            lines.append(f"| gilded         | {s['gilded_score']}     | {meta['gilded']} gold |")
            if s["verdict_score"] > 0:
                lines.append(f"| verdict (AITA) | {s['verdict_score']}    | flair: {meta['flair']} |")
            lines.append("")

            lines.append("**Proposed hooks** (TikTok-first, violation/wrongness-first):")
            for h in c["hook_variants"]:
                lines.append(f"- `{h}`")
            lines.append("")
            lines.append("**Alternative settings** (dodge clichés):")
            for sv in c["setting_variants"]:
                lines.append(f"- {sv}")
            lines.append("")
            lines.append(f"**Premise paraphrase (for stub)**: {c['premise_paraphrase']}")
            lines.append("")
            lines.append(f"**Stub me**: `python scripts/research_reddit_stories.py --stub {c['id']}`")
            lines.append("")
            lines.append("<details><summary>📄 source selftext (copyrighted — do NOT copy verbatim)</summary>")
            lines.append("")
            lines.append("```")
            # Safe-truncate selftext display to discourage casual copy-paste of long bodies
            ellipsis = "…\n[truncated for display — open the source URL for full text]" if len(c["selftext"]) > 1500 else ""
            lines.append(c["selftext"][:1500] + ellipsis)
            lines.append("```")
            lines.append("")
            lines.append("</details>")
            lines.append("")
            lines.append("---")
            lines.append("")

    atomic_write_text(out_path, "\n".join(lines))
    return out_path


def write_json_report(candidates_by_cluster: dict[str, list[dict]], limit: int) -> Path:
    RESEARCH_DIR.mkdir(parents=True, exist_ok=True)
    out_path = RESEARCH_DIR / f"candidates_{date.today().isoformat()}.json"
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "limit_per_cluster": limit,
        "clusters": {
            name: [
                {k: v for k, v in c.items() if k != "selftext"}  # drop selftext from JSON to keep file small
                for c in items[:limit]
            ]
            for name, items in candidates_by_cluster.items()
        },
    }
    atomic_write_json(out_path, payload, indent=2)
    return out_path


# ---------------------------------------------------------------------------
# Stub materializer
# ---------------------------------------------------------------------------

def write_stub(candidate: dict, sy_number: int) -> Path:
    """Write story_queue/SY_NN_<letter>_<slug>.md from a candidate dict."""
    letter = candidate["cluster_letter"]
    cluster = candidate["cluster"]
    voice_info = VOICE_ASSIGNMENTS[letter]
    slug = slugify(candidate["title"])
    sy_id = f"SY_{sy_number:02d}_{letter}_{slug}"
    out_path = QUEUE_DIR / f"{sy_id}.md"

    # Read SY_TEMPLATE for structure cues — but write our own to ensure
    # the deterministic paraphrase lands in Premise, never selftext.
    cluster_name_titled = cluster.title()

    body_lines = [
        f"# {sy_id} — [WRITER: choose a 4-6 word working title]",
        "",
        "**Status:** QUEUED",
        f"**Subgenre:** {cluster}",
        f"**Voice:** {voice_info['voice']}     <!-- override here if POV is female; see SY_TEMPLATE.md for options -->",
        "**Narrator gender:** M  <!-- change to F if first-person narrator is female (recommended for any 'my husband'/'my wife' framing) -->",
        f"**Model:** {voice_info['model']}",
        "",
        "## Premise",
        candidate["premise_paraphrase"],
        "",
        "## Hook angle",
        "Pick ONE of the proposed hooks below (or write a better one matching the formula):",
    ]
    for h in candidate["hook_variants"]:
        body_lines.append(f"- `{h}`")
    body_lines.extend([
        "",
        "## Protagonist (survival only)" if letter == "S" else "## Protagonist",
        ("[Same continuity-protagonist if this is a numbered survival arc — see prior SY_*_S_* entries. "
         "Otherwise: tall man late 30s, weathered face, dark hair, faded jacket.]"
         if letter == "S"
         else "[N/A for this sub-genre — Reddit + horror don't carry cross-video protagonist continuity.]"),
        "",
        "## Visual style notes",
        "Defaults inherit from `story_script_writer.TEMPLATES`. Override here if needed:",
        "- Palette: [optional override]",
        "- Avoid: [optional]",
        "",
        "## Alternative settings (dodge cliché)",
    ])
    for sv in candidate["setting_variants"]:
        body_lines.append(f"- {sv}")
    body_lines.extend([
        "",
        "## Notes",
        f"**Source** (tone reference only — never quote verbatim): {candidate['url']}",
        f"**Reddit post id**: `{candidate['id']}`",
        f"**Subreddit**: r/{candidate['subreddit']}",
        f"**Mined score**: {candidate['score']['total']}/100 ({cluster_name_titled} cluster)",
        "",
        "⚠️ The source post is COPYRIGHTED by its author. The writer must apply the "
        "playbook's anti-plagiarism rule: different word choices, restructured narrative, "
        "anonymized names + locations, paraphrased dialogue. Verbatim risks a YouTube strike.",
        "",
    ])

    atomic_write_text(out_path, "\n".join(body_lines))
    return out_path


def materialize_stubs(candidates_by_cluster: dict[str, list[dict]], top_n: int, dry_run: bool) -> list[Path]:
    """Round-robin S → R → H → S → R → H... taking top_n from each."""
    # Build interleaved order
    queues = {
        "S": list(candidates_by_cluster.get("survival", []))[:top_n],
        "R": list(candidates_by_cluster.get("reddit",   []))[:top_n],
        "H": list(candidates_by_cluster.get("horror",   []))[:top_n],
    }
    interleaved: list[dict] = []
    for i in range(top_n):
        for letter in ("S", "R", "H"):
            if i < len(queues[letter]):
                interleaved.append(queues[letter][i])

    if dry_run:
        print("\n  [dry-run] would create the following stubs:")
        n = next_sy_number()
        for i, c in enumerate(interleaved):
            slug = slugify(c["title"])
            print(f"    SY_{(n+i):02d}_{c['cluster_letter']}_{slug}  ← r/{c['subreddit']} (score {c['score']['total']})")
        return []

    created: list[Path] = []
    next_num = next_sy_number()
    for offset, candidate in enumerate(interleaved):
        path = write_stub(candidate, next_num + offset)
        created.append(path)
        print(f"  ✓ stub: {path.relative_to(PROJECT_ROOT)}  (score {candidate['score']['total']})")
    return created


def materialize_single_stub(candidate_id: str, json_report_path: Path | None) -> Path | None:
    """Find a candidate by id in the most recent JSON report and stub it."""
    if json_report_path is None:
        # Fall back to most recent
        candidates = sorted(RESEARCH_DIR.glob("candidates_*.json"), reverse=True)
        if not candidates:
            print("ERROR: No candidate JSON report found. Run /research-stories first.", file=sys.stderr)
            return None
        json_report_path = candidates[0]
    try:
        payload = json.loads(json_report_path.read_text())
    except (json.JSONDecodeError, OSError) as e:
        print(f"ERROR: Could not read {json_report_path}: {e}", file=sys.stderr)
        return None

    for cluster_name, items in payload.get("clusters", {}).items():
        for c in items:
            if c["id"] == candidate_id:
                # Restore selftext = empty (paraphrase doesn't need it)
                c.setdefault("selftext", "")
                path = write_stub(c, next_sy_number())
                print(f"  ✓ stub: {path.relative_to(PROJECT_ROOT)}  (score {c['score']['total']})")
                return path
    print(f"ERROR: candidate id '{candidate_id}' not found in {json_report_path}", file=sys.stderr)
    return None


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_windows(spec: str) -> list[tuple[str, str | None]]:
    """Parse 'week,month,year,hot' into [('top','week'), ..., ('hot',None)]."""
    out: list[tuple[str, str | None]] = []
    for token in spec.split(","):
        t = token.strip().lower()
        if t == "hot":
            out.append(("hot", None))
        elif t in ("week", "month", "year", "all", "day"):
            out.append(("top", t))
        else:
            print(f"WARN: unknown window '{t}' — ignored", file=sys.stderr)
    return out or DEFAULT_WINDOWS


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cluster", choices=["horror", "reddit", "survival"], default=None,
                        help="Restrict mining to one cluster (default: all 3).")
    parser.add_argument("--limit", type=int, default=30,
                        help="Top N per cluster shown in the report (default 30 for bulk, 10 in single-cluster mode).")
    parser.add_argument("--windows", default="week,month,year,hot",
                        help="Comma-separated rankings/time-windows to mine. Default: week,month,year,hot")
    parser.add_argument("--stub", metavar="POST_ID",
                        help="Materialize ONE pre-filled queue stub from a candidate id (looks in the latest report).")
    parser.add_argument("--stub-top", type=int, metavar="N",
                        help="Batch-materialize the top N per cluster (round-robin S,R,H,S,R,H,...).")
    parser.add_argument("--dry-run", action="store_true",
                        help="With --stub-top, print what would be stubbed without writing.")
    parser.add_argument("--skip-mine", action="store_true",
                        help="Skip mining (use latest candidates_*.json). Useful for --stub-top after a fresh mine.")
    args = parser.parse_args()

    # --stub <id>: needs latest report, no fresh mine required
    if args.stub:
        path = materialize_single_stub(args.stub, json_report_path=None)
        return 0 if path else 1

    # --stub-top with --skip-mine: read latest report and stub from it
    if args.skip_mine and args.stub_top:
        candidates_paths = sorted(RESEARCH_DIR.glob("candidates_*.json"), reverse=True)
        if not candidates_paths:
            print("ERROR: --skip-mine but no prior report exists. Drop --skip-mine.", file=sys.stderr)
            return 2
        payload = json.loads(candidates_paths[0].read_text())
        candidates_by_cluster = {name: items for name, items in payload["clusters"].items()}
        # Reconstitute dicts to match mine_all's shape
        materialize_stubs(candidates_by_cluster, args.stub_top, args.dry_run)
        return 0

    # Default: mine, write report, optionally stub
    windows = parse_windows(args.windows)
    if args.cluster and args.limit == 30:
        args.limit = 10  # narrower mode = smaller report

    print(f"── Reddit Story Research ──")
    print(f"  Clusters: {args.cluster or 'all 3'}")
    print(f"  Windows:  {windows}")
    print(f"  Limit:    top {args.limit} per cluster")
    print()

    candidates_by_cluster = mine_all(args.cluster, windows)
    if not any(candidates_by_cluster.values()):
        print("\nERROR: No candidates passed filters. Reddit may be down, subreddits may be private, "
              "or the rate limit is engaged. Try again in 10 minutes.", file=sys.stderr)
        return 1

    md_path = write_markdown_report(candidates_by_cluster, args.limit)
    json_path = write_json_report(candidates_by_cluster, args.limit)

    print(f"\n  ✓ Markdown report: {md_path.relative_to(PROJECT_ROOT)}")
    print(f"  ✓ JSON report:     {json_path.relative_to(PROJECT_ROOT)}")
    print()
    for cluster_name in ("horror", "reddit", "survival"):
        items = candidates_by_cluster.get(cluster_name, [])
        if not items:
            continue
        top = items[0]
        print(f"  {cluster_name.title():<9} top: [{top['score']['total']}] {top['title'][:60]}")

    if args.stub_top:
        print(f"\n── Batch-stubbing top {args.stub_top} per cluster ──")
        materialize_stubs(candidates_by_cluster, args.stub_top, args.dry_run)

    print()
    print(f"  Next: review {md_path.name}, then either:")
    print(f"    python scripts/research_reddit_stories.py --stub <candidate_id>     # single stub")
    print(f"    python scripts/research_reddit_stories.py --stub-top 5 --skip-mine  # batch (no re-mine)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
